### ISSUE TITLE
Fix absolute path in ExportVariablesHandler

### ISSUE THREAD

**Issue by nachorequeno** [dice-project/DICE-Simulation#10]
In Linux platforms, the instruction to create a URI in the ExportVariablesHandler handler returns an file-system absolute path instead of a workspace-based absolute path.

The line 47 should be changed from:

```
URI uri = URI.createFileURI(path.toFile().toString());
```

to

```
URI uri = URI.createPlatformResourceURI(path.toString(), true);
```

**Comment by abelgomez** [comment]
This was already fixed long time ago in aa03a0e0ea2b85b5cf7261f29060297ee989714e. Closing.
