### ISSUE TITLE
Change Menu and Preferences groups

### ISSUE THREAD

**Issue by marcgise** [dice-project/DICE-Simulation#2]
Change the Menu and Preferences groups of Simulation Tools in order adapt to the general Menus and Preferences contributed by "org.dice.ui" plugin for DICE. Have a look at this plugin to know the ID of the contributions.

**Comment by abelgomez** [comment]
Just to make it clear (there's no link), I suppose you are referring to [this plugin](https://github.com/dice-project/DICE-Platform/tree/master/org.dice.ui), isn't it?

We will update the Simulation Tools categories in the next release.
