### ISSUE TITLE
Images are skipped during the calibration process

### ISSUE THREAD

**Issue by navylemdi** [dice-project/DICE-Simulation#35]
Hello, I'm Yvan, a mechanical engineer student working on DIC. We tried to do a calibration with our new camera. We would like to use DICe as a DIC algorithm.
We tried to do a calibration with DICe however lot of images were skipped even when we tried to play with the calibration option. In comparison, we also tried to do a calibration with VIC3D and we obtain good results.
Have you an idea of why images are skipped with DICe?
Here is a link to access our images: https://drive.google.com/drive/folders/1Qz_nyVJez9Q0A1REdjzHSJU7IH0AyVcr?usp=sharing
Thanks for considering my request,
Yvan

**Comment by abelgomez** [comment]
Dear @navylemdi , could it be possible you confused the DICE Simulation Tool (https://github.com/dice-project/DICE-Simulation) with the DICe Engine (https://github.com/dicengine/dice)?

😃

**Comment by navylemdi** [comment]
Oh, you're right! I'm very confused to disturbed you 
Thank you for your response.

**Comment by abelgomez** [comment]
No worries! 🙂
