### ISSUE TITLE
Current target platform is no longer valid with the release of Eclipse 4.6.1

### ISSUE THREAD

**Issue by abelgomez** [dice-project/DICE-Simulation#5]
With the release of Eclipse 4.6.1, some of the update sites referenced in the target platform no loger contain the versions specified in it (e.g., http://download.eclipse.org/eclipse/updates/4.6).

Either the plugin versions must be upgraded or the target platform must be changed to use specific builds.

**Comment by abelgomez** [comment]
@perezp , I'm working in some extensions to the DICE Simulation Tools, and fixing this is a pre-requisite for me.

I take charge of fixing and sending a PR.

**Comment by perezp** [comment]
Thank you @abelgomez !!
